---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo check
        run: cargo check --all-targets --all-features
      - name: cargo test
        run: cargo test --all --locked --all-features
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
